import type { Metadata } from "next";
import { Noto_Kufi_Arabic } from "next/font/google";
import "styles/globals.css";

const kufi = Noto_Kufi_Arabic({ subsets: ["arabic"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ar" dir="rtl">
			<body className={kufi.className}>
				<div>{children}</div>
			</body>
		</html>
	);
}
